development:
  adapter: postgresql
  encoding: unicode
  database: salarios_development
  username: vquaiato
  host: localhost
test:
  adapter: postgresql
  encoding: unicode
  database: salarios_test
  pool: 5
  username: vquaiato
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: salarios_production
  pool: 5
  username: postgres
  host: localhost
